sul-dlss/stanford-arclight

- config/deploy.rb
The Capfile is locked to an earlier version of Capistrano, while the Gemfile
version has been updated. Locking version in the Capfile seems to be inconsistent with our deployment practices elsewhere in the
portfolio. This is currently preventing us from deploying the app.
> Unpin Capistrano version

- lib/traject/sul/normalized_title.rb
- lib/traject/sul_component_config.rb
- lib/traject/sul_config.rb
Sets title to "[NO TITLE PROVIDED]" for components without a title or date. We will request guidance from archivists about whether we should form a title differently or if these components need remediation.
Relates to #381 and closes #376
> Override NormalizedTitle to compensate for components without a title or date

- app/services/aspace_client.rb
This query broke after we upgraded ASpace versions. A little digging around the ASpace code revealed: https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/advanced_query_string.rb#L48
> ASpace v3.3.1 requires precision param for date queries

- Gemfile
- Gemfile.lock
This will unblock dependency updates and let us upgrade after winter close, see: https://github.com/sul-dlss/stanford-arclight/issues/404
> pin arclight to v1.0.*

- app/controllers/catalog_controller.rb
- spec/features/facets_spec.rb
- spec/fixtures/ead/uarc/sc0097.xml
Closes #442.
The existing fixture XML file didn't have anything that was "online". I added an additional file from the Knuth papers that does.
After:
> Move access facet to top and expand by default

- config/repositories.yml
These may not be the final images but would rather see them than broken links every day :)
Before
After
> Fix broken thumbnail links

- Gemfile
- Gemfile.lock
A side effect of this update is:
Fixes #468 
This update is a breaking change, specifically around the formatting of component identifiers.
See:
https://github.com/projectblacklight/arclight/wiki/Indexing-EAD-in-ArcLight#for-implementers-upgrading-beyond-v101
We will need to reindex any local data being used in development, as well as what's on the demo site, so it may be best to hold this PR til we have a plan for that.
> Breaking change: Update Arclight to 1.1.2

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/sulCollection.scss
- app/components/arclight/sidebar_component.html.erb
Closes #439
This also adds scrolling to the collection overview/contents as discussed. This does not impact the sidebar when it is presented as a mobile menu.
 
For pages with significant front matter, I think this works well:
http://localhost:3000/catalog/ars0124aspace_ref42_5kr
For pages with a smaller amount of front matter, I'm more ambivalent about it (but we've established I have different tastes about this!):
http://localhost:3000/catalog/ars0124aspace_ref136_xr6
Reasons being in this case we could ideally be reducing the size of the scrollable sidebar by not just the header height, but potentially some proportion of the footer as well, depending on the height of the right panel content. Duke gets around this by not having a footer. Michigan has similar behavior as here. …
> Make the collection sidebar sticky and scrolling

- config/repositories.yml
Fixes #367
The catalog controller references 'contact' (or contact_html, which is how Core has it set up).
> Edit the contact key in repositories.yml

- app/components/arclight/group_component.html.erb
- app/components/arclight/repository_location_component.html.erb
- app/views/arclight/repositories/_repository.html.erb
- spec/features/repositories_page_spec.rb
Closes #429.
In Slack we also discussed changing the repository link in this same way in other areas. I will PR that separately if/when we are happy with how this is done.
> Link repositories directly to collection search results

- app/components/breadcrumb_component.rb
- app/components/breadcrumbs_hierarchy_component.rb
- app/components/repository_breadcrumb_component.html.erb
- app/components/repository_breadcrumb_component.rb
- app/components/search_result_breadcrumbs_component.rb
- app/controllers/catalog_controller.rb
- spec/features/catalog_spec.rb
- spec/features/collection_spec.rb
Fixes #485.
Chasing down more repository links that need to link to the search page.
> Link repositories to their search page in breadcrumbs

- solr/conf/schema.xml
- solr/conf/solrconfig.xml
Fixes #490 
These changes make it so that searches in All Fields and Identifier return expected results for the following queries:
ARS-0043
ARS-0043xml
ARS-0043.xml
ARS-0043-xml
ARS-0043 xml
ARS.0043
ARS.0043xml
ARS.0043.xml
ARS.0043-xml
ARS.0043 xml
ARS0043
ARS0043xml
ARS0043.xml
ARS0043-xml
ARS0043 xml
ARS 0043
ARS 0043xml
ARS 0043.xml
ARS 0043-xml
ARS 0043 xml
> Solr config/schema updates for improved id search

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/bootstrapVariables.scss
- app/assets/stylesheets/palette.scss
- app/assets/stylesheets/stanfordStripe.scss
- app/assets/stylesheets/sulBase.scss
- app/assets/stylesheets/sulHeader.scss
- app/components/arclight/masthead_component.html.erb
- app/components/arclight/search_bar_component.html.erb
- app/components/blacklight/search_navbar_component.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_stanford_stripe.erb
Closes #492.
I bring in some blacklight component templates here, you'll likely need to restart rails to pick them up.
A link to the feedback form was specified, but I'm assuming the feedback form will be done in another issue?
@astridu reviewed this via screenshare. We agreed we may revisit the navbar search controls layout at small sizes, but it wasn't a blocker.
> Page Header Redesign

- app/services/aspace_client.rb
- spec/services/aspace_client_spec.rb
When numbered_cs is set to true, ASpace will output numbered tags (e.g., c01 rather than c).
https://archivesspace.github.io/archivesspace/api/#get-an-ead-representation-of-a-resource
RuboCop felt all the lines were too long, which is why it isn't added inline.
I tested this with one `DownloadEadJob.enqueue_one_by` job and it worked as expected.
> Add numbered_cs param when fetching EAD XML

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/views/shared/_top_navbar.html.erb
Closes #503 
See https://github.com/projectblacklight/blacklight/blob/6c6a72066a6330a815603e839b316958f6321dd7/app/controllers/concerns/blacklight/controller.rb#L54 for why removing `render_bookmarks_control?`
> Remove Login from navbar

- Rakefile
This change is necessary so that the seed data is indexed using the local traject configurations and not the traject configurations from upstream arclight.
> Use the IndexEadJob to index the EAD seed data

- app/controllers/catalog_controller.rb
Citation still shows up under Access and Use.
Closes #438
> Remove citation from summary

- README.md
- app/controllers/download_controller.rb
- app/jobs/download_ead_job.rb
- app/models/solr_document.rb
- config/downloads.yml
- config/routes.rb
- config/settings.yml
- lib/traject/sul_config.rb
- spec/models/solr_document_spec.rb
- spec/rails_helper.rb
- spec/requests/download_spec.rb
Closes #434 
Because this relies on the filename being stored in Solr we'll need to re-index after this is merged.
> Enable download of EAD file

- app/assets/stylesheets/sulHeader.scss
- app/assets/stylesheets/sulLanding.scss
Closes #516.
The spacing was indeed pure chaos at different scaling levels. I couldn't figure a good way of handling this with markers, so I went back to using pseudo elements here. Is there a better way anybody knows of?
The non-landing page header has this same problem so I'm attempting to sneak that in here too.
> Fix spacing on inline lists

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/sulFacets.scss
- app/controllers/catalog_controller.rb
- app/models/search_builder.rb
- config/routes.rb
Closes #523 
Some of the JavaScript driven features (sliders and histogram) do not work with Blacklight 8 (see upstream issues: https://github.com/projectblacklight/blacklight_range_limit/issues/236), but it does support entering a date range.
Display with facet is not applied
Display when facet is applied
> Add and configure blacklight_range_limit gem

- app/assets/stylesheets/palette.scss
- app/assets/stylesheets/sulHeader.scss
- app/assets/stylesheets/sulLanding.scss
- app/components/landing_page_search_bar_component.html.erb
Closes #525.
Brings the autocomplete and search icon back in from the Blacklight component:
Doesn't look like it'll conflict, but we might want to wait until #513 is merged. This PR would be way easier to rebase if needed.
> Add autocomplete and search icon to landing page

- app/assets/stylesheets/sulHeader.scss
- app/controllers/catalog_controller.rb
- config/locales/en.yml
> Change links in header

- config/environments/production.rb
This reverts commit 4d9c62131e50003f5985ff29ad907658e4a3438c.
When logging to `STDOUT` the application logs get redirected to `/var/log/apache2/error.log`. One advantage of this set up instead of logging to `production.log` is that the logs automatically get sent to CloudWatch without additional configuration in puppet. See discussion on https://github.com/sul-dlss/stanford-arclight/issues/532
> Revert "Wrap config that sends logs to STDOUT in an ENV flag"

- app/models/solr_document.rb
- app/views/arclight/requests/_aeon_web_ead.html.erb
- config/repositories.yml
- spec/features/request_spec.rb
- spec/models/solr_document_spec.rb
- spec/rails_helper.rb
Closes #510 
This wires up Aeon requesting without enabling the request feature via the repositories.yml config. If you want to test this locally un-comment one of the request_types config sets for one of the repositories.
> Set up Aeon requests but leave configurations commented out

- README.md
- lib/tasks/stanford_arclight.rake
I found while working on https://github.com/sul-dlss/stanford-arclight/issues/550 that in order for Solr to correctly delete a parent and all its children (nested documents) you must delete by id and not by query.
> Fix rake task for deleting a collection and its children

- app/assets/stylesheets/sulLanding.scss
- app/components/arclight/masthead_component.html.erb
- app/components/landing_page_search_bar_component.html.erb
- app/views/landing_page/index.html.erb
- config/locales/en.yml
- spec/features/home_page_spec.rb
Closes #538
Closes #554 
Closes #552 
Fulfilling #538 (make headers bold) does make the text appear bolder than in the Figma designs, but I went ahead with that since we discussed it as a team. 
Here's how it's looking:
> Update landing page design

- app/views/landing_page/_featured_item_teasers.html.erb
- config/settings.yml
Closes #524.
This is the way Duke and Michigan do it.
https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/blob/main/config/featured_images.yml?ref_type=heads
We need the additional `image_alt` because alt text was specified in the original landing page issue (Duke and Michigan use a background image with no alt text).
I only added a link to the one image because it's the only one that has a corresponding link in demo currently.
> Allow featured image captions to have links

- app/assets/stylesheets/featuredItemTeasers.scss
- app/assets/stylesheets/sulLanding.scss
- app/views/landing_page/_featured_item_teasers.html.erb
- app/views/landing_page/index.html.erb
- spec/features/home_page_spec.rb
Closes #540 
The image is randomly selected with the `.sample` method on each page load. 
Heads up, I did `rake assets:clobber` and hard refreshed before the CSS looked right.
> Replace image carousel with single featured image

- app/jobs/download_ead_job.rb
- app/jobs/index_ead_job.rb
- lib/traject/sul_config.rb
- spec/jobs/download_ead_job_spec.rb
- spec/jobs/index_ead_job_spec.rb
Closes #564 
I opted to only index the resource_uri and the repository_uri on the collection document which is all we need to handle automated deletes. I'll set up the delete job in a separate PR.
> Index the EAD source repository on the collection

- app/assets/stylesheets/sulBase.scss
We display "This site is protected by reCAPTCHA and the Google [Privacy Policy](https://policies.google.com/privacy) and [Terms of Service](https://policies.google.com/terms) apply" in the feedback form so we don't need to display the badge on every page.
Closes #569
> Hide recaptcha badge

- app/assets/stylesheets/sulHeader.scss
- app/assets/stylesheets/sulLanding.scss
Fixes border issue reported in slack
Makes magnifying glass icon have padding to look more like mockups.
> Style tweaks for the search bar

- app/jobs/delete_ead_job.rb
- app/services/aspace_client.rb
- spec/jobs/delete_ead_job_spec.rb
- spec/services/aspace_client_spec.rb
Closes #550 
This doesn't schedule the job to run. I thought we'd do that when we work on the configuration specified in #424
> Add job to delete finding aids unpublished in aspace

- app/controllers/catalog_controller.rb
- spec/features/collection_spec.rb
Closes #443.
Also changes the collection page test feature spec to actually visit a collection, which I missed the first time around.
> Display call number on collection pages

- app/components/arclight/search_bar_component.html.erb
- app/components/landing_page_search_bar_component.rb
- app/javascript/controllers/search_form_controller.js
- spec/features/search_spec.rb
- spec/rails_helper.rb
Closes #544.
I make a small modification to the ask here, by grouping by "all results" when searching within a collection. This is explained in #544. We should wait for @dinahhandel or @corylown to weigh in before accepting.
> Change default search grouping to 'collection'

- app/assets/stylesheets/sulLanding.scss
Not requested, feel free to discard. This is my own personal pet peeve.
Changes the focus styling on the landing page search to encompass the search button.
Old:
New:
Does not modify any behavior on the other pages.
> Adjust landing page search focus styling

- Gemfile
- Gemfile.lock
sul-arclight-demo is now on postgres. We'll just let sul-arclight-prod hum along on mysql until we switch over to the new load-balanced prod VMs and then shut it down.
> Switch from mysql to postgres in production

- app/assets/stylesheets/palette.scss
- app/assets/stylesheets/sulCollection.scss
- app/components/arclight/online_content_filter_component.html.erb
- app/components/arclight/online_status_indicator_component.html.erb
- app/components/arclight/online_status_indicator_component.rb
- app/components/arclight/search_result_title_component.html.erb
- app/controllers/catalog_controller.rb
- app/javascript/application.js
Part of #602 but does not close it -- still need to customize the facet
00/10369813-7ba6-40a9-baf7-2bae42fc2caa">
b-a51588dee856">
> Implement custom digital contents icon, tooltip, and alert

- app/assets/stylesheets/sulHeader.scss
This gets us this far on #534 
As for making the "X" nicer looking, we may need to wait on[ this Blacklight PR]( https://github.com/projectblacklight/blacklight/pull/3153 ) in order to properly style it. I couldn't get very far with the invalid `<button-tag>`
> Limit the width of flash alerts

- app/assets/stylesheets/sulCollection.scss
Closes #617 
@corylown I went with your suggestion to do nothing if hovering over the non-actionable text of the constraint.
(hover state on the X button:)
> Refine hover colors for search constraints

- app/assets/stylesheets/sulLanding.scss
Closes #604 if I understood @taylor-steve correctly!
With this change:
> Remove list styles from autocomplete dropdown

- app/services/aspace_client.rb
- app/services/aspace_query.rb
- spec/services/aspace_client_spec.rb
Generalizes the base subqueries, having them trigger conditionally based
on params/options. Removes the interior specifics around "resource"
queries versus "other" queries. Starts the renaming process, moving from
"component" (my mistake!) to what I think is a clearer "record" when
talking about generalized results from ASpace.
Paves the way for the queries needed for #557.
> Refactor the Aspace Query

- app/controllers/landing_page_controller.rb
- app/views/landing_page/_cards.html.erb
- spec/controllers/landing_page_controller_spec.rb
Closes #620.
Caches the library hours fragment on the landing page cards partial. It needed to be a fragment cache as the hours API object isn't serializable. Expires the cache at the next half hour because the libraries tend to open/close at the half hour.
Unsurprisingly this is much faster, 2.1ms versus ~750ms to fetch fresh:
```shell
17:15:07 web.1  | Read fragment views/landing_page/_cards:2de8cc75cc02aa10e3b2c517d27da179/location_hours (0.1ms)
17:15:07 web.1  |   Rendered landing_page/_cards.html.erb (Duration: 2.1ms | Allocations: 1917) [cache hit]
```
Remember to `touch tmp/caching-dev.txt` and restart if testing locally.
> Cache the library hours

- config/sidekiq.yml
Dialing back concurrency so maybe we can generate PDFs without bringing the VMs to a halt.
> Set sidekiq concurrency to 3

- app/jobs/download_ead_job.rb
- app/models/aspace/repository.rb
- app/services/aspace_client.rb
- app/services/aspace_query.rb
- app/services/aspace_search_query.rb
- app/services/concerns/aspace_paginated_query.rb
- spec/jobs/download_ead_job_spec.rb
- spec/models/aspace/repository_spec.rb
- spec/services/aspace_client_spec.rb
- spec/services/aspace_paginated_query_spec.rb
- spec/services/aspace_query_spec.rb
- spec/services/aspace_search_query_spec.rb
Closes #557.
Changes `DownloadEadJob` so that it can detect when a resource (or a contained record) has a linked agent that has been updated. This allows us to update the finding aid in situations where ArchivesSpace does not report the resource itself as modified, similar to #556.
- The Aspace client page handling has been moved into `AspacePaginatedQuery`
- There is a new query type `AspaceSearchQuery` that uses the `q:search` syntax. The linked agent data was inaccessible to the `aq` query
- `check_component_dates` is now `check_record_dates` and will trigger both the sub-resource level (e.g., archival object) and the linked agent check
- Find an agent that's linked to a published, unsuppressed resource (or one of its records) in a harvestable repository (e.g., ars).
- Use one of the …
> Update finding aid when a linked agent has changed

- lib/traject/sul/normalized_id.rb
- lib/traject/sul_config.rb
- spec/features/collection_spec.rb
- spec/features/search_spec.rb
- spec/fixtures/ead/cubberley/toulouse.xml
- spec/requests/download_spec.rb
This normalizer is basically copied from some of @corylown's existing work. 
Closes #436 
Creates IDs that look like (check URL bar) ~
> Provide custom id normalizer for Solr documents

- app/jobs/generate_pdf_job.rb
- app/xslt/ead_to_fo.xsl
Fixes #633 with the exception of the invalid metadata files that have been documented.
- Defines a placeholder namespace 'ns2' during PDF generation. Some OAC elements use this but as we know, OAC strips namespace definitions.
- Adds handling for nested `controlaccess` elements
- Adds handling for nested `indexentry` elements
- Prevents some identifier duplications
These changes should be OAC specific. ArchivesSpace doesn't seem to generate EAD XML that uses these (valid) features. This has been tested on a subset (~200) of previously working files with no new failures.
It should not be necessary to regenerate PDFs for ASpace EADs. Existing PDFs from OAC EADs could benefit slightly from being regenerated if they use `indexentry` elements with multiple sub-elements. The display for those …
> Update PDF config to better handle OAC EADs

- lib/traject/sul/normalized_id.rb
- spec/lib/traject/sul/normalized_id_spec.rb
In cases where we're missing an eadid we're getting ids like `_native-american-alumni-oral-histories` instead of `native-american-alumni-oral-histories`.
> Handle empty string arguments in NormalizedId

- app/jobs/generate_pdf_job.rb
- spec/jobs/generate_pdf_job_spec.rb
Fixes the error I introduced in #645.
Using `2>&1` with Open3 is not the recommended approach.
> Stop using stderr redirection for PDF generation

- app/assets/stylesheets/cards.scss
- app/assets/stylesheets/sulLanding.scss
- app/components/arclight/header_component.html.erb
- app/views/landing_page/index.html.erb
- app/views/repositories/_browse_repositories.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_stanford_stripe.erb
- spec/features/home_page_spec.rb
Addresses the following issues from #651:
- Global 1: Stanford Stripe header
- Homepage 1: level 1 heading
- Homepage 2: italicized text
- Browse all repositories: skipped h2
Other issues will be/have been addressed upstream or in separate PRs.
> Fix accessibility issues

- app/components/arclight/sidebar_component.html.erb
- app/models/solr_document.rb
- spec/features/collection_spec.rb
- spec/fixtures/ead/cubberley/cubb1967.xml
Part of #651.
Previous behavior was to display an empty list. Lists have an implicit aria role of "list". Containers with that role should not be empty.
Before:
After:
> Hide collection contents in sidebar when empty

- Gemfile
- Gemfile.lock
- app/jobs/generate_pdf_job.rb
- config/schedule.rb
- spec/jobs/generate_pdf_job_spec.rb
Currently we only check for the existence of the PDF file as a success condition during PDF generation. Apache FOP is good at cleaning up after itself if the generation process fails, but if the job is terminated for any reason, a malformed file will remain.
Changes:
- Adds the pdf-reader gem, used to check that the generated PDF is valid
- Adds a `enqueue_all_missing_and_invalid` method to GeneratePdfJob, which is scheduled.
- For the purposes of `skip_existing`, an invalid PDF file does not count as 'existing'
Tested on demo by faking a malformed PDF and running `GeneratePdfJob.enqueue_all_missing_and_invalid`.
> Improve PDF validation in PDF generation job

- app/assets/stylesheets/palette.scss
- app/assets/stylesheets/stanfordStripe.scss
- app/assets/stylesheets/sulBase.scss
- app/assets/stylesheets/sulHeader.scss
- app/components/arclight/header_component.html.erb
- app/components/arclight/masthead_component.html.erb
- app/views/shared/_beta_banner.html.erb
- app/views/shared/_beta_tag.html.erb
- config/locales/en.yml
- config/settings.yml
- spec/features/beta_banner_spec.rb
Closes #657.
Removes the beta tag as requested. Main pages checked with Siteimprove, no new issues were introduced.
> Add the public beta banner

- app/assets/stylesheets/sulBase.scss
- app/assets/stylesheets/sulFacets.scss
The facet modals (any facet with a 'more >>' link) still have some old styling elements.
Old:
New:
> Update facet modal style to use new design

- app/assets/stylesheets/sulCollection.scss
Fixes #669 
Firefox/Chrome handled this differently -- the style was invalid since the element is not a flex container itself. But Chrome somehow knew to render it correctly. 
Firefox now:
> Use valid style for Digital Content text

- app/controllers/download_controller.rb
- app/models/solr_document.rb
- app/overrides/document_downloads_override.rb
- app/services/document_local_file_mapper.rb
- config/downloads.yml
- spec/models/solr_document_spec.rb
- spec/services/document_local_file_mapper_spec.rb
Part of #660.
Displays download links only for files that exist and have a non-zero size.
- Push logic of where EAD XML/PDFs live on the local file system out of DownloadController to a service
- Implement ArcLight download size accessors that use the service
- Patch ArcLight DocumentDownloads to filter based on size
If we wanted to go this direction, there's an argument to be made for refactoring `GeneratePdfJob` to also use the service.
> Remove EAD download links for missing files

- app/assets/stylesheets/sulHeader.scss
- app/components/blacklight/top_navbar_component.html.erb
- spec/features/feedback_form_spec.rb
Closes #684.
This is maybe a bit silly but throwing this in a turbo frame seemed excessive? Open to it...
It does need to be an inline style. At the point in which the page looks like the screenshot in the issue, neither our CSS nor Bootstrap's CSS is available yet.
> Hide feedback form during page loads

- app/controllers/landing_page_controller.rb
- spec/controllers/landing_page_controller_spec.rb
Might close #685?
I'm not sure if it is *the* bug but I do believe this fixes *a* bug.
Currently it is possible to try to set a cache time that's too close to the current time. In my dev environment, setting the cache time to `Time.current + 0.4.seconds` using the Redis cache reliably creates a cache key with no expiry time. I suspect the point at which this occurs will vary depending on performance.
Here I pad the time with 5 seconds if it's close, to give the cache system a minimum time difference.
> Adjust library hours cache timing

- app/components/blacklight/top_navbar_component.html.erb
By default it gets set to the application title, which is wrong in this case.
> Set correct link title for library logo link

- config/initializers/sidekiq.rb
This should prevent cron emails from being sent with just the Sidekiq connecting to Redis message
> Configure sidekiq log for both client and server

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
JS imports are broken in Blacklight 8.2
Commit that broke it: projectblacklight/blacklight@d8c0ec4
Proposing a revert: projectblacklight/blacklight#3164
> Pin blacklight to 8.1.0 until JS in 8.2 is fixed

- app/jobs/generate_pdf_job.rb
- config/sidekiq.yml
- spec/jobs/generate_pdf_job_spec.rb
Addresses part of #660.
Apache FOP is exceeding the default Java max heap size on prod (1024m) for large (15+ MB) XML files. This increases the max heap to 2024m during FOP execution. This does not alter the initial size of the heap, so this should only impact the system in 2 known cases.
> Increase max heap size during PDF generation

- app/assets/stylesheets/sulCollection.scss
- app/views/kaminari/blacklight/_next_page.html.erb
- app/views/kaminari/blacklight/_paginator.html.erb
- app/views/kaminari/blacklight/_prev_page.html.erb
Closes #600. It's backlogged, not sure if we want it or not.
New:
> Update paginator to match design

- app/components/embed_component.rb
- app/controllers/catalog_controller.rb
The current `embed_component.html.erb` is present but not being used (from https://github.com/sul-dlss/stanford-arclight/commit/2be2c02b972a69c9f471a68ba3df2c5b155711de), which is also causing our local OembedViewerComponent to not be used. This hooks it up, if that's what we want.
I spot tested a few and couldn't notice a difference other than the slightly increased bottom margin. OembedViewerComponent switches the stimulus (?) controller to 'sul-embed'. I could use another set of eyes on that.
> Use our embed component template

- app/models/digital_object.rb
- spec/models/digital_object_spec.rb
Fixes the case of https://archives.stanford.edu/catalog/ars0238_walking-dead-record-label-and_aspace_49ba1a5eac42903f24fb0a985e643dc4 that has an href with a trailing tab, which causes the PURL regex to fail.
This is literally the only case of this I can find where the whitespace results in a failure, so I'd be happy to not merge this and fix the data.
There are ~20 hrefs with trailing newlines, but they are complete URLs and work just fine as is.
> Strip leading and trailing whitespace from hrefs

- app/assets/stylesheets/sulHeader.scss
This reverts commit 2ef4d369578b0792dc7d5d1d436494de093cb502.
This didn't fix our contrast issue. I opened https://github.com/sul-dlss/stanford-arclight/issues/712 to address this.
> Revert "Use dark link color for beta banner to meet contrast requirements

- app/assets/stylesheets/sulHeader.scss
I'm not bothering with variables because this banner is going to go away after the production launch and we're not using this background color anywhere else.
Barely noticeable difference from the official stanford colors, but these meet the contrast requirements for level A and AA compliance on the yellow background.
> Fix beta banner contrast

- app/assets/stylesheets/sulHeader.scss
This is necessary after https://github.com/projectblacklight/blacklight/pull/3166 so that the search form uses the full area.
> Stretch the search element to fill the container

- app/assets/stylesheets/sulHeader.scss
- spec/features/feedback_form_spec.rb
Fix for this repo's part of #734.
Use visibility rather than display so the transition animation still works as expected.
If we're fine with this approach I can do VT as well.
> Prevent keyboard focus on hidden feedback form

- app/controllers/bookmarks_controller.rb
Closes #731 
I'm not sure yet what we want to do about the group by controls in ArcLight core. For now, let's shut them off in our app.
> Turn off group toggle for the bookmarks view

- app/controllers/landing_page_controller.rb
- app/services/time_service.rb
- spec/services/time_service_spec.rb
Non-endpoint methods of a rails controller should be private.  We needed to extract the TimeService into it's own module so that it could be tested directly.
> Make controller methods private

- app/components/using_these_materials_component.html.erb
Siteimprove wants headings to be structured on collection/component pages.
> Change using these materials heading

- app/components/arclight/masthead_component.html.erb
Otherwise both navbar and col-md-4 apply different padding, which can make alignment difficult
Ref https://github.com/projectblacklight/arclight/pull/1551
> Extract col-md-4 outside the navbar

- app/assets/stylesheets/sulHeader.scss
- app/components/arclight/masthead_component.html.erb
> Fix unbalanced margin on topbar when feedback open

- app/components/blacklight_range_limit/range_form_component.html.erb
The BS4 submit button from blacklight_range_limit is only visually hidden, it can still be tabbed to/is accessible to screen readers.
> Remove Bootstrap 4 submit button

- app/components/blacklight/top_navbar_component.html.erb
- spec/features/feedback_form_spec.rb
Closes #774
Similar to what https://github.com/ambethia/recaptcha recommends for v3, executing reCAPTCHA at submit time rather than setting a timer to refresh it every two minutes.
I kept it inline because the name/action that determine the names of the helper functions from the recaptcha gem are here. 
There are at least 3 other sites that will need something similar.
> Execute reCAPTCHA on form submit

- app/assets/stylesheets/sulBase.scss
- app/components/arclight/masthead_component.html.erb
- app/components/user_util_links_component.html.erb
- spec/features/navbar_spec.rb
This matches the DLSS component designs https://www.figma.com/design/K1syTsalaB1nlRftgOi0Pw/DLSS-Components\?node-id\=0-1\&t\=FOLafWldFP9lbzqm-0
Wider screens
Narrow screens with hamburger open
Narrow screens with hamburger closed
> Move collections and repositories link into the hamburger menu

- app/components/arclight/search_bar_component.html.erb
- app/components/landing_page_search_bar_component.rb
- app/components/search_button_component.rb
> Use local component for search button

- app/controllers/landing_page_controller.rb
- app/services/time_service.rb
- app/views/landing_page/_cards.html.erb
- spec/services/time_service_spec.rb
The bug from https://github.com/sul-dlss/stanford-arclight/issues/685 happened again.
Upon inspection, the redis ttl for the cache key was `-1` for on both prod and stage. Once that's cleared, they work fine for a while. I know of at least two values that result in a `-1` ttl for `expires_at`:
* nil
* A time in the past
We had a guard in place for times in the past, but maybe it didn't account for all situations. This PR switches to using `expires_in` with a value with stricter bounds which is hopefully safer.
> Use expires_in for library hours cache

- app/assets/stylesheets/sulCollection.scss
- config/locales/blacklight.en.yml
Fixes #916 
Fixes #826 
Before:
After:
> Update pagination to match designs/component library

- solr/conf/schema.xml
- solr/conf/solrconfig.xml
- solr/conf/stopwords_punctuation.txt
- spec/features/search_spec.rb
Fixes #698 (modeled on this arclight change: https://github.com/projectblacklight/arclight/pull/1590/commits/0cb0910aa28dc650487925418a3e8580d317780a)
> Fix searches containing standalone punctuation

- config/locales/blacklight.en.yml
Based on the arclight figma designs we had removed the `<strong>` tag around components of the pagination translations, but after discussion with the team we decided we want the default blacklight behavior.
> Use default blacklight pagination translations

- app/assets/stylesheets/componentLibraryOverrides.css
- app/assets/stylesheets/sulBase.css
- app/assets/stylesheets/sulCollection.scss
- app/assets/stylesheets/sulHeader.scss
- app/assets/stylesheets/sulLanding.scss
Ref https://github.com/sul-dlss/stanford-arclight/issues/909
It wasn't easy to contain the changes to a single area of the page / single ticket. My feeling is that we could chip away at these smaller tickets but not close #909 until we do a thorough design review.
Closes:
#871 
#932
#917 
#918 
#922 
#921 
Impacted, but more work needed to close:
#919 -- bookmarks -- the svg fill color is changed but we need the new icon
#914 -- facet selections -- the button colors and hover states are now aligned with the design, but the new language "Your selections" and "Clear all" button need to be implemented
> Align colors with component library

- app/assets/stylesheets/palette.css
- app/assets/stylesheets/sulCollection.scss
> Update number of items badge design

- app/assets/stylesheets/sulBase.css
> Fix view type button size

- app/components/arclight/document_component.html.erb
- app/components/arclight/group_component.html.erb
- app/components/arclight/online_status_indicator_component.rb
- app/components/arclight/search_result_title_component.html.erb
- app/components/collection_context_component.html.erb
- app/components/collection_unitid_pill_component.html.erb
- app/components/extent_pill_component.html.erb
Fixes #948 
This is a bit fiddly, but I think it overall looks better at more window widths than the initial implementation.
> Adjust call number pill so it looks good whether wrapped or not

- app/assets/stylesheets/palette.css
- app/assets/stylesheets/sulHeader.scss
- app/components/arclight/search_bar_component.html.erb
- app/components/blacklight/icons/search_component.rb
- app/components/search_button_component.rb
- config/locales/en.yml
- spec/features/search_spec.rb
Not done here:
- changing the carets for dropdowns to be filled in solid
- the X feature in the text area
Also, this is the last sub ticket from https://github.com/sul-dlss/stanford-arclight/issues/909 ! Can we close after this is merged?
> Implement new search bar design

- app/components/collection_context_component.html.erb
> Adjust margin and display of collection title

- app/assets/stylesheets/sulLanding.scss
> Remove serif fonts from landing page

- app/assets/stylesheets/cards.scss
> Set border radius for repository cards

- app/assets/stylesheets/sulLanding.scss
- app/components/landing_page/info_card_component.html.erb
> Add vertical line between info cards on landing page

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/groupedResults.css
- app/components/arclight/group_component.html.erb
- config/locales/en.yml
> Restyle grouped by collection results

- app/assets/stylesheets/sulCollection.css
- app/components/arclight/sidebar_component.html.erb
- app/components/blacklight/icons/chevron_down_component.rb
- app/components/collection_overview_component.html.erb
- app/components/collection_overview_component.rb
- spec/features/collection_overview_spec.rb
Closes https://github.com/sul-dlss/stanford-arclight/issues/907
> Make the collection sidebar overview section collapsible

- app/assets/stylesheets/sulBase.css
> Adjust bookmarks count pill style

- app/assets/stylesheets/sulBase.css
https://github.com/sul-dlss/stanford-arclight/issues/913 is merged so this style can be removed.
> Remove unused style

- app/assets/stylesheets/sulCollection.css
- app/components/arclight/online_status_indicator_component.rb
- app/components/arclight/search_result_title_component.html.erb
- app/controllers/catalog_controller.rb
Fixes #848 
This brings us inline with the Arclight design and configuration pattern for this component. It differs in location from what is proposed in the issue, but is much more straightforward to implement.
Before:
After:
> Configure digital icon to appear to document contents list

- config/locales/en.yml
> Update download link translations

- app/assets/stylesheets/sulCollection.css
> Update collection digital content banner styles

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/sulBase.css
- app/assets/stylesheets/sulHeader.css
- app/assets/stylesheets/sulLanding.css
- app/assets/stylesheets/sulSearchbar.css
- app/components/arclight/search_bar_component.html.erb
- app/components/blacklight/search_navbar_component.html.erb
- app/components/landing_page_search_bar_component.html.erb
- app/components/landing_page_search_bar_component.rb
- app/components/search_button_component.rb
- app/components/search_tips_link_component.html.erb
Closes #980
I had to reorganize the `sulHeader.css` file in order to really understand what was going on. It may look like a ton of changes but most of it is just reorganization -- hopefully not confusing.
Here are all the iterations:
> Make searchbar design responsive

- app/assets/stylesheets/sulCollection.css
- app/components/blacklight/icons/external_link_component.rb
- app/components/embed_component.html.erb
- app/components/embed_component.rb
- spec/components/embed_component_spec.rb
We might want to consolidate some of these digital card styles, but I'll do that as a separate PR after this is merged.
Only links:
Embed and links:
> Wrap non-embeddable digital resources in a bootstrap card

- app/assets/stylesheets/sulLanding.css
- app/views/landing_page/index.html.erb
> Adjust landing page search/image area layout

- app/components/landing_page/user_util_links_component.html.erb
- spec/features/navbar_spec.rb
> Render utility links (bookmarks, history) on landing page

- app/assets/stylesheets/sulBase.css
- app/components/arclight/sidebar_component.html.erb
- app/components/collection_context_component.html.erb
- app/components/document_download_component.html.erb
- app/components/document_download_component.rb
> Adjust collection context box to match designs

- app/components/landing_page/library_hours_component.rb
- config/settings.yml
- spec/components/landing_page/library_hours_component_spec.rb
Fixes #952 
Adds configured link to the hours info:
> Link to library hours from LibraryHoursComponent

- app/assets/stylesheets/sulCollection.css
Noticed this while doing other work that the background color was not right.
Before:
After
> Set background of collection info box to fog-light

- app/assets/stylesheets/cards.css
- app/assets/stylesheets/groupedResults.css
- app/assets/stylesheets/sulBase.css
- app/assets/stylesheets/sulCollection.css
This moves Bootstrap card styles into `cards.css` and de-duplicates some styles (drop shadow, border, etc.) shared across these cards. No impact to display.
Example card:
> Refactor and de-duplicate Bootstrap card styles

- app/assets/stylesheets/sulBase.css
- app/components/alert_component.html.erb
- app/components/alert_component.rb
- app/components/blacklight/icons/bootstrap_check_circle_fill_component.rb
- app/components/blacklight/icons/bootstrap_exclamation_circle_fill_component.rb
- app/components/blacklight/icons/bootstrap_exclamation_triangle_fill_component.rb
- app/components/blacklight/icons/bootstrap_info_circle_fill_component.rb
- app/components/blacklight/top_navbar_component.html.erb
- app/views/shared/_flash_msg.html.erb
Closes #534
I believe only `info` icon/alert styles are used in this app.
But, in case the Blacklight system flash generates any type other than `info`, it is good have the entire set of options available.
> Align alerts and flash messages with component library

- app/assets/stylesheets/cards.css
- app/assets/stylesheets/sulCollection.css
- app/components/access_component.html.erb
- spec/features/collection_spec.rb
Closes #865
(underline on hover)
> Make the Access and Use section collapsible

- app/assets/stylesheets/cards.css
- app/assets/stylesheets/sulCollection.css
- app/components/using_these_materials_component.html.erb
- app/components/using_these_materials_component.rb
- spec/components/using_these_materials_component_spec.rb
Part of #845 
I will add styles to the Access and Use section in a separate PR
This PR adds the "Using these materials" card.
> Redesign using these materials box

- Gemfile
- Gemfile.lock
- app/components/blacklight/icons/export_component.rb
- app/components/bookmark_tools_component.html.erb
- app/components/bookmark_tools_component.rb
- app/controllers/bookmarks_controller.rb
- app/services/csv_service.rb
- app/views/bookmarks/index.csv.erb
- app/views/bookmarks/index.html.erb
- config/initializers/mime_types.rb
- config/locales/en.yml
- spec/components/bookmark_tools_component_spec.rb
- spec/services/csv_service_spec.rb
Part of https://github.com/sul-dlss/stanford-arclight/issues/882
Fixes #885 
Adds export to CSV link with messaging about how bookmarks are saved/stored:
Export works by exporting a full page of bookmarks, so an alert shows if there are multiple pages of bookmarks. I've bumped the default per page setting to 50 so this should be avoided in most cases.
This only addresses the CSV export. I thought it made sense to address the send to email feature as separate work.
> Add download bookmarks to CSV

- app/controllers/catalog_controller.rb
- app/models/search_builder.rb
- spec/models/search_builder_spec.rb
Fixes #1034
This only impacts the sort order when relevance is selected (or no sort order is selected -- defaulting to relevance).
When results are grouped and there is no query supplied: each of the groups will sort by collection title and the components within each group will sort in component order with the collection last.
When results are NOT grouped and there is no query supplied: the results will be sorted in component order starting with the collection (so all collections will be listed in title order first):
> Use sort_isi as the fallback when there is no relevancy score

- app/components/search_context/null_server_applied_params_component.html.erb
- app/components/search_context/null_server_applied_params_component.rb
- app/controllers/catalog_controller.rb
> Turn off "Clear all" and "Back to search" controls on show pages

- app/components/collection_source_component.html.erb
Current -- looks a bit crowded:
This change:
> Increase padding above collection source component

- Gemfile
- Gemfile.lock
- config/initializers/rack_attack.rb
Fixes #911 
Related puppet PR to set the RACK_ATTACK_REDIS_URL environment variable in prod https://github.com/sul-dlss/puppet/pull/12338
> Configure Rack Attack and use Redis as the cache store

- app/views/layouts/blacklight.html.erb
We've done this elsewhere: https://github.com/sul-dlss/SearchWorks/pull/4322
Turning this off will reduce requests and may help prevent real users from encountering rack-attack throttling.
> Turn off turbo prefetch

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/popovers.css
- app/assets/stylesheets/sulCollection.css
- app/components/arclight/online_content_filter_component.html.erb
- app/components/arclight/online_status_indicator_component.html.erb
- app/components/arclight/online_status_indicator_component.rb
- app/components/digital_content_facet_component.html.erb
- app/components/digital_content_facet_component.rb
- app/components/online_content_popover_component.html.erb
- app/components/online_content_popover_component.rb
- app/javascript/application.js
- spec/components/online_content_popover_component_spec.rb
> Convert digital content tooltip to a popover

- app/assets/stylesheets/cards.css
- app/assets/stylesheets/sulBase.css
- app/controllers/using_this_site_controller.rb
- app/views/using_this_site/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/home_page_spec.rb
Closes #881
- Since the text on this page is so highly customized, especially the 7 paragraphs in `How to search` I wasn't sure how much of it to put into `en.yml` -- I am happy to move it over if that is preferred.
> Add the Using this site page

- app/components/arclight/group_component.html.erb
> Display digital content icon in grouped results headers

- app/components/arclight/group_component.html.erb
> Set lh-base class on grouped title so underlines are not cramped on hover

- app/views/bookmarks/_clear_bookmarks_widget.html.erb
- app/views/search_history/index.html.erb
> Use btn-outline-secondary for clear bookmarks and search history buttons

- app/components/embed_component.html.erb
- app/components/oembed_viewer_component.html.erb
- app/javascript/controllers/online_content_controller.js
- app/javascript/controllers/sul_embed_controller.js
- spec/features/online_content_links_spec.rb
- spec/fixtures/ead/uarc/sc0097.xml
Fixes #1087 
This adds the possibly embed-able link to the list of displayed list of online content links, dispatches an event once we're sure the embed is really an embed, and removes the link if that event fires. This way if the purl isn't an embed the link it appears styled and within the same list as any other links if they exist.
Before:
After:
> Watch for an embed success and remove the displayed link

- app/components/extent_pill_component.html.erb
- app/components/extent_pill_component.rb
- spec/components/extent_pill_component_spec.rb
> Join and truncate extents for pill display

- app/components/document_body_collection_component.html.erb
- app/components/embed_component.html.erb
Fixes #1124 
Possibly controversial...
We seem to have more collections with online content at the collection level and the current display doesn't look great. This moves the online content below the first metadata section.
Before:
After:
> Move online content below first metadata section for collections

- app/javascript/controllers/search_form_controller.js
- spec/features/search_spec.rb
It doesn't make sense to group results by collection when the results are limited only to collections.
> Do not group results when the results are limited to collections

- app/assets/stylesheets/sulCollection.css
This CSS does the shadow style border:
~~ 
I thought the plain line looked pretty good too and matched the rest of the screen. Could change to that if desired.
> Add bottom border to sidebar scroll section

- app/services/aspace_client.rb
- config/settings.yml
- spec/services/aspace_client_spec.rb
Partially addresses #1129 
There will be some follow-on work to catch this error when enqueuing jobs and reverting the a full re-index, since it's likely that many/most objects have been updated if we reach this limit.
> Guard against queries that are too large for ASpace/Solr

- app/jobs/download_ead_job.rb
- app/services/enqueue_repository_download.rb
- spec/services/enqueue_repository_download_spec.rb
This refactors some of the complicated repository download enqueuing logic to a service class and adds handling for `ArgumentErrors` from the `ASpaceClient`, indicating we should follow an alternate indexing strategy (download everything in the repository instead of trying to sort out what has changed).
> Add a EnqueueRepositoryDownload service to handle enqueuing bulk download jobs.

- app/jobs/delete_ead_job.rb
- config/settings.yml
- spec/jobs/delete_ead_job_spec.rb
Fixes #1138 
If we get a large number of finding aids to delete it's likely something went wrong so we should raise an error instead. If after investigation the deletes look legitimate the job can be run manually by overriding the safeguard.
> Guard against large numbers of automated deletes

- app/services/aspace_repositories.rb
This data doesn't change much so we don't need send a request to ASpace every time we need it.
> Cache repositories response from ASpace for one hour

- lib/traject/sul_config.rb
I will add a test that will make use of this field in the follow up work to use ARKs for deletes.
> Index the ARK shoulder on each collection

- app/models/aspace/repository.rb
- app/services/aspace_repositories.rb
- spec/models/aspace/repository_spec.rb
- spec/services/aspace_repositories_spec.rb
Part of #1141 
This does not require that ARKs or ARK shoulders exist yet in ASpace, but provides the ability to use them once they do exist.
> Make Aspace::Repository ark_shoulder aware

- lib/traject/sul_component_config.rb
- spec/features/ark_spec.rb
- spec/fixtures/ead/uarc/sc0097.xml
We removed this extra info from collections here https://github.com/sul-dlss/stanford-arclight/commit/708be15e48fb02dbe9620622bad84db9960edc6b but we also need to remove it from components.
> Also remove ARK info from components

- app/jobs/delete_ead_job.rb
- app/services/solr_paginated_query.rb
- spec/jobs/delete_ead_job_spec.rb
- spec/services/solr_paginated_query_spec.rb
This pulls solr querying logic currently used in the delete job out to its own service class so I can use it as part of https://github.com/sul-dlss/stanford-arclight/pull/1156/files where I need a largely similar query.
> Move paged solr querying logic to its own class

- app/jobs/delete_ead_job.rb
- app/jobs/download_ead_job.rb
- app/jobs/index_ead_job.rb
- app/services/aspace_client.rb
- lib/traject/sul_config.rb
- spec/jobs/delete_ead_job_spec.rb
- spec/jobs/download_ead_job_spec.rb
- spec/jobs/index_ead_job_spec.rb
- spec/services/aspace_client_spec.rb
Fixes #1141 
Hold until we have ARKs generated in ASpace prod. Then we can deploy this to prod and kick off a full reindex.
> Use ARKs to handle deletes; remove uses of indexed resource URI

- config/settings.yml
We're hitting the current limit of 500 boolean clauses more often than I expected and I think it's safe to bump this up to 900 to avoid unnecessary re-indexing.
> Bump boolean clause limit to 900

- config/deploy.rb
- config/deploy/prod.rb
Based on https://github.com/sul-dlss/dlss-capistrano/blob/cd4766654f600888ecb32bc3f18ff3735de9555e/lib/dlss/capistrano/tasks/sidekiq_systemd.rake#L4 I think this is what's needed to let capistrano manage sidekiq on the background/worker vms in prod
> Configure capistrano to manage sidekiq on background vms
