Capfile
Gemfile
Gemfile.lock
Rakefile
config/deploy.rb
config/deploy/demo.rb
config/deploy/prod.rb

Add deploy scripts for demo and prod.

---

.solr_wrapper.yml

In anticipation of an sul-solr impending solr upgrade.

Update .solr_wrapper.yml to use 7.4.0

---

config/deploy.rb

@anarchivist 
Hoping this fixes 👇
```
02:14 honeybadger:deploy
Notifying Honeybadger of deploy.
01 No value provided for required options '--api-key'
```

Add Honeybadger to linked files

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/mixins.scss
app/assets/stylesheets/sul_variables.scss

The aim here is to just setup a basic set of styles that we can move forward with more of #91 with.

Add base styles from MyLibrary part of #91

---

config/downloads.yml

ArcLight will assume this config is in place in a generated app.

Update downloads default needed for ArcLight update

---

app/controllers/catalog_controller.rb

Fix in Blacklight already coming in https://github.com/projectblacklight/blacklight/pull/2369

Fixes #164 by working around bug introduced in Blacklight v7.12.1

---

config/deploy.rb

Fixes `NoMethodError: undefined method `>' for nil:NilClass`

Set the rails_env for clearing the cache

---

app/models/solr_document.rb
spec/models/solr_document_spec.rb

Guard for cases where collections are lower level components

---

Gemfile
Gemfile.lock
app/jobs/download_ead_job.rb
app/jobs/index_ead_job.rb
app/services/aspace_client.rb
config/deploy.rb
config/environments/production.rb
config/routes.rb
spec/jobs/download_ead_job_spec.rb
spec/jobs/index_ead_job_spec.rb
spec/rails_helper.rb

~~Waiting on https://github.com/sul-dlss/operations-tasks/issues/3542~~
~~Closes #387~~

Add sidekiq; add EAD download and indexing jobs

---

app/jobs/download_ead_job.rb
app/services/aspace_repositories.rb
spec/jobs/download_ead_job_spec.rb
spec/services/aspace_repositories_spec.rb

This seems more like a service than a model.

Move AspaceRepositories to app/service

---

config/schedule.rb

This helps keep my inbox clean.

This prevents the cron from logging the Sidekiq startup message

---

app/controllers/catalog_controller.rb

Related to https://github.com/sul-dlss/stanford-arclight/issues/451

Rename Identifier to Call Number in search dropdown

---

app/controllers/catalog_controller.rb

Remove All Fields search option

---

config/settings.yml

Change URL for Green Library

---

Gemfile.lock
app/controllers/download_controller.rb
spec/requests/download_spec.rb

Return 404 if EAD file does not exist

---

app/controllers/download_controller.rb
app/xslt/ead_remove_namespace.xsl
spec/requests/download_spec.rb

Add option to download an EAD without namespaces

---

config/environments/production.rb

Wrap config that sends logs to STDOUT in an ENV flag

---

config/locales/arclight.en.yml
config/locales/blacklight.en.yml

Change application name to "Archival Collections at Stanford"

---

app/components/blacklight/start_over_button_component.rb
spec/features/search_spec.rb

Override the Blacklight start_over_button_component to add group=true

---

Gemfile
Gemfile.lock

New prod and stage environments will use postgres. The existing prod and demo environments use mysql, so we need both for now.

Add pg gem for new prod and stage environments

---

Gemfile
Gemfile.lock

This reverts commit 1f892521f4ece45ab13c4ea0612c65891f9a8dfe.
I'll create a branch just for the postgres setup until we're fully off mysql

Revert "Add pg gem for new prod and stage environments"

---

app/jobs/delete_ead_job.rb
app/jobs/download_ead_job.rb
app/models/aspace/repository.rb
app/services/aspace_repositories.rb
spec/jobs/delete_ead_job_spec.rb
spec/jobs/download_ead_job_spec.rb
spec/models/aspace/repository_spec.rb
spec/services/aspace_repositories_spec.rb

This will help us (in a future refactor) remove some complexity from DownloadEadJob.

Add Aspace::Repository model

---

app/assets/stylesheets/sulCollection.scss

Remove border radius for badges in grouped search results

---

app/assets/stylesheets/featuredItemTeasers.scss
config/settings.yml

Closes #479.
None of these items are on demo, so for now I've linked to the purl so at least folks can view the entire image.

Update featured items on landing page

---

app/assets/stylesheets/sulCollection.scss

This PR addresses @astridu 's comments after #595 was merged.

Adjust styles

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/initializers/sidekiq.rb

Some setup for our separately hosted redis instances on stage and prod

Read redis connection info from ENV

---

config/repositories.yml

Part of https://github.com/sul-dlss/stanford-arclight/issues/452

Update repository descriptions for Manuscripts and UARC

---

app/assets/stylesheets/sulCollection.scss

Override AL Core for expand/collapse hierarchy SVG icons

---

config/locales/arclight.en.yml

Remove colons from metadata field labels

---

app/services/arclight_repository_mapper.rb
config/repositories.yml
spec/jobs/download_ead_job_spec.rb
spec/services/arclight_repository_mapper_spec.rb

Add rare books repository and mapping info

---

public/robots.txt

Ban all bots in robots.txt

---

app/assets/stylesheets/sulCollection.scss

Change the active color for AL actions dropdown

---

app/jobs/generate_pdf_job.rb
spec/jobs/generate_pdf_job_spec.rb

Now that I've stared at 100+ of these Apache FOP error logs, I have a better idea of what somebody would need to see to know how to address a PDF generation failure.
This reduces the amount of console spam when generating PDFs and when a GeneratePdfError is raised it'll have more context:
```log
Failed to generate PDF for /Users/sctaylor/Development/stanford-arclight/data/stage/sc1210.xml. (GeneratePdfJob::GeneratePdfError)
SEVERE: Error while rendering page 5. Reason: java.lang.IllegalStateException: java.net.URISyntaxException: Illegal character in scheme name at index 0: %20http://purl.stanford.edu/dt262bj7930
SEVERE: javax.xml.transform.TransformerException: java.net.URISyntaxException: Illegal character in scheme name at index 0: %20http://purl.stanford.edu/dt262bj7930
```

Add message to PDF generation error

---

app/overrides/parents_override.rb

Let Arclight::Parents#eadid be nil

---

app/assets/stylesheets/sulCollection.scss
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_using_these_materials.html.erb
config/locales/en.yml
config/repositories.yml
spec/features/collection_spec.rb

Add "Using these materials" links to collections

---

config/schedule.rb

Schedule DeleteEadJob to run every 6 hours

---

lib/traject/sul_component_config.rb
lib/traject/sul_config.rb

Remove blank creator_ssim field values before indexing

---

config/repositories.yml

Part of #452  -- not sure if it closes it, however.
Update: I noticed that the text in #452 for Cubberley had not been added to the app. I think the text is honestly more helpful before this change, but I was going off the ticket comments. Happy to remove that commit if desired.

Update East Asia Library and Cubberley description text

---

config/locales/en.yml

No visual changes, just cleaning up these long IDs.
Old:
New:

Add missing section translations

---

app/jobs/download_ead_job.rb
app/models/aspace/resource.rb
app/services/arclight_repository_mapper.rb
app/services/aspace_query.rb
spec/jobs/download_ead_job_spec.rb
spec/models/aspace/resource_spec.rb
spec/services/arclight_repository_mapper_spec.rb

Don't require an EAD ID from ASpace in order to download resource

---

app/controllers/landing_page_controller.rb
spec/features/home_page_spec.rb

Configure autocomplete on landing page

---

app/components/blacklight/top_navbar_component.html.erb

Add analytics to data-controller attribute

---

config/locales/en.yml

Change content warning message link

---

app/assets/stylesheets/sulBase.scss
app/assets/stylesheets/sulCollection.scss
app/views/arclight/requests/_aeon_web_ead.html.erb

Let's make it green on the off chance it gets turned on at some point before it gets moved/styled for real.
Old:
New:

Style the request button

---

app/assets/stylesheets/application.sass.scss
app/assets/stylesheets/sulBase.scss
app/assets/stylesheets/sulFacets.scss
app/assets/stylesheets/sulFooter.scss

Footer link hover state color should be white

---

app/helpers/application_helper.rb
app/helpers/blacklight_helper.rb

Add BlacklightHelper to control for load order

---

app/jobs/delete_ead_job.rb

Use explicit block when referenced in method

---

app/jobs/delete_ead_job.rb

@jcoyne thanks for you comment on https://github.com/sul-dlss/stanford-arclight/pull/754. I think this is the right fix for #753 that also keeps rubocop happy.

Run rubocop autocorrect but keep block_given?

---

app/assets/stylesheets/sulHeader.scss

I mistakenly left this in as part of https://github.com/sul-dlss/stanford-arclight/pull/755. It's unused (and mistargeted) currently.

Remove unused CSS

---

app/components/blacklight/top_navbar_component.html.erb

We no longer have a feedback controller, so this property can be removed

Remove obsolete property for feedback controller

---

app/assets/stylesheets/sulHeader.scss
app/components/blacklight/top_navbar_component.html.erb

This makes the css simpler as we don't need to override the bg-dark styles

Remove feedback from the bg-dark

---

app/components/arclight/masthead_component.html.erb

The containing flex box does the centering

Remove unnecessary text-center classes

---

config/deploy.rb

We now get this from an env variable
Fixes #793

Remove config/secrets.yml

---

app/components/landing_page_search_bar_component.html.erb

Provide a background for autocomplete dropdown

---

config/locales/en.yml

Closes [#846](https://github.com/sul-dlss/stanford-arclight/issues/846)

Edit the harmful language link

---

config/schedule.rb
lib/tasks/stanford_arclight.rake

Add and schedule tasks to prune user and search data

---

config/locales/en.yml
spec/features/home_page_spec.rb

Edit wording for Ask a subject specialist card

---

app/assets/stylesheets/componentLibraryOverrides.css
app/assets/stylesheets/sulHeader.scss
app/components/arclight/search_bar_component.html.erb
app/components/blacklight/icons/outline_info_component.rb
app/components/blacklight/search_navbar_component.html.erb
app/components/search_tips_component.html.erb
app/components/search_tips_component.rb
app/components/search_tips_link_component.html.erb
app/components/search_tips_link_component.rb
app/controllers/catalog_controller.rb
config/locales/en.yml
config/routes.rb
spec/components/search_tips_component_spec.rb
spec/components/search_tips_link_component_spec.rb

Closes #874
Thanks to @hudajkhan for already doing the work in Exhibits.

Implement search tips feature

---

app/components/search_tips_component.html.erb
solr/conf/schema.xml

Switch to EnglishMinimalStemFilterFactory

---

app/assets/stylesheets/palette.css
app/assets/stylesheets/sulBase.css
app/components/arclight/document_component.html.erb
app/components/arclight/group_component.html.erb
app/components/arclight/search_result_title_component.html.erb
app/components/arclight/sidebar_component.html.erb
app/components/collection_context_component.html.erb
app/components/collection_context_component.rb
app/components/collection_unitid_pill_component.html.erb
app/components/collection_unitid_pill_component.rb
app/components/extent_pill_component.html.erb
app/components/extent_pill_component.rb
spec/components/collection_context_component_spec.rb
spec/components/collection_unitid_pill_component_spec.rb
spec/components/extent_pill_component_spec.rb

Display call number next to collection title

---

app/assets/stylesheets/sulBase.css
app/components/arclight/document_component.html.erb
app/controllers/catalog_controller.rb

It's possible doing this in AL Core is desired?
Closes #919

Use Blacklight's bookmark icon

---

app/components/blacklight/constraints_component.html.erb
app/components/blacklight/start_over_button_component.rb
config/locales/en.yml
spec/features/search_spec.rb

Update constraints selection design

---

app/assets/stylesheets/sulCollection.scss
app/controllers/catalog_controller.rb
spec/features/digital_content_filter_spec.rb

Update design for digital content filter

---

app/assets/stylesheets/sulBase.css
app/assets/stylesheets/sulCollection.scss

Update facet design

---

app/assets/stylesheets/sulHeader.scss
app/assets/stylesheets/sulLanding.scss
app/components/landing_page_search_bar_component.html.erb

Search box adjustments

---

config/repositories.yml

Update repository descriptions

---

Gemfile
Gemfile.lock
app/views/shared/_flash_msg.html.erb
config/initializers/global_alerts.rb
config/settings.yml

Add global alerts

---

app/assets/stylesheets/cards.css
app/assets/stylesheets/sulCollection.css
app/assets/stylesheets/sulHeader.css
app/assets/stylesheets/sulLanding.css

After looking at https://github.com/sul-dlss/stanford-arclight/pull/719 to see if we could bring it up to date I decided there had been too much change and it would be easier to open a new PR to convert our SASS stylesheets to CSS.

Remove sass

---

app/components/arclight/document_component.html.erb
app/components/collection_context_component.html.erb
spec/components/collection_context_component_spec.rb

Move request button to collection context box

---

app/assets/stylesheets/sulCollection.css

Let component library style remove X

---

app/assets/stylesheets/application.sass.scss
app/assets/stylesheets/sulBreadcrumbs.css
app/assets/stylesheets/sulCollection.css
app/components/breadcrumbs_hierarchy_component.html.erb

Use a flat structure to display breadcrumbs

---

app/assets/stylesheets/sulBreadcrumbs.css

Adjust breadcrumb styles for both pages and collection hierarchy

---

app/controllers/catalog_controller.rb

Turn autocomplete off for now

---

app/assets/stylesheets/sulBase.css

Closes #966 
I clicked through the screens to make sure this didn't break any layouts. Would appreciate a double check.

Keep footer pushed to bottom of page

---

app/assets/stylesheets/cards.css
app/components/access_component.html.erb
app/components/access_component.rb
app/components/access_metadata_layout_component.rb
app/controllers/catalog_controller.rb

Restyle access and use section

---

app/components/oembed_viewer_component.rb

Allow title to display in viewer header

---

Gemfile
Gemfile.lock
config/initializers/cors.rb

See https://github.com/sul-dlss/SearchWorks/issues/4805

Add CORS headers to /catalog so that Searchworks can query

---

lib/traject/sul/normalized_id.rb
spec/features/collection_spec.rb
spec/features/search_spec.rb
spec/lib/traject/sul/normalized_id_spec.rb
spec/requests/download_spec.rb

Prefer the ead id for normalized ids; fallback on title

---

app/components/document_collection_controls_component.html.erb
app/components/document_collection_controls_component.rb
app/views/catalog/hierarchy.html.erb
spec/components/document_collection_controls_component_spec.rb

Add per page widget to contents list

---

app/components/collection_context_component.html.erb
app/components/collection_context_component.rb
spec/components/collection_context_component_spec.rb

Link collection from title in context component

---

app/services/aspace_client.rb
config/initializers/okcomputer.rb

Add optional OkComputer checks

---

app/assets/stylesheets/sulCollection.css
app/assets/stylesheets/sulHeader.css
app/components/arclight/masthead_component.html.erb
app/components/arclight/sidebar_component.html.erb
app/components/collection_context_component.html.erb
app/components/landing_page/masthead_component.html.erb
config/locales/en.yml

Improve mobile styles for the collection sidebar

---

app/components/arclight/search_result_title_component.html.erb

Adjust line height of titles in results

---

app/assets/stylesheets/sulCollection.css

Make open/close chevron thicker

---

app/controllers/catalog_controller.rb
app/services/csv_service.rb
spec/services/csv_service_spec.rb

Add repository to Export/Email fields

---

app/assets/stylesheets/sulCollection.css

Add border under online content

---

app/overrides/document_downloads_override.rb

Sort PDF files first followed by EAD

---

config/repositories.yml

Update visit notes for all repositories

---

app/controllers/catalog_controller.rb

Add Component ID to component display metadata

---

app/assets/stylesheets/application.sass.scss
app/assets/stylesheets/loadingPlaceholder.css

Customize the loading contents animation

---

app/assets/stylesheets/sulCollection.css
app/components/arclight/document_component.html.erb

Remove border from around breadcrumbs on show page

---

app/models/search_behavior/digital_content_sort.rb
app/models/search_builder.rb
spec/models/search_builder_spec.rb

Move collections last when browsing digital content

---

app/xslt/ead_to_fo.xsl

Add author and sponsor to PDF cover page

---

app/controllers/catalog_controller.rb

Use checkbox for bookmark control for accessibility

---

app/xslt/ead_to_fo.xsl

Use non-filing title for PDF if available

---

app/assets/stylesheets/sulLanding.css
app/assets/stylesheets/sulSearchbar.css
app/components/landing_page_search_bar_component.html.erb
app/components/search_button_component.rb
app/components/search_tips_link_component.html.erb
app/components/search_tips_link_component.rb

Add search tips to the landing page search bar

---

app/components/arclight/group_component.html.erb
app/components/arclight/search_result_title_component.html.erb

Let call number pill wrap with title

---

lib/traject/sul_config.rb
spec/features/ark_spec.rb

Do not index extra ARK-related unitid elements

---

app/components/using_these_materials_component.rb
spec/components/using_these_materials_component_spec.rb

Display more of the restriction text in UsingTheseMaterialsComponent

---

app/controllers/feedbacks_controller.rb

Setting a minimum score seems to be required now.

Set min recaptcha score

---

app/views/layouts/blacklight.html.erb
config/settings.yml

This is needed for verification with Google Search Console

Add google site verification meta tag for Search Console

---

config/locales/arclight.en.yml

Change repository_location display label

---

config/deploy.rb
config/deploy/prod.rb

Related ops task: https://github.com/sul-dlss/operations-tasks/issues/4168

Set up deploys for separate worker VMs
